name: PR Details
description: Please provide a brief description of what this PR does
title: '[PR]:'
body:
  - type: textarea
    attributes:
      label: Description of the change
      description: Expected content
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reason for the change
      description: provide steps to reproduce the problem
    validations:
      required: true
  - type: input
    attributes:
      label: Link to original source
  - type: markdown
    attributes:
      value: |-
        If this pull request closes an issue, add the issue number: 
        Closes #
